DROP TABLE IF EXISTS altnames CASCADE;
DROP TABLE IF EXISTS doma CASCADE;
DROP TABLE IF EXISTS flat CASCADE;
DROP TABLE IF EXISTS kladr CASCADE;
DROP TABLE IF EXISTS socrbase CASCADE;
DROP TABLE IF EXISTS street CASCADE;
