#!/bin/bash

#Скрипт установки классификатора адресов КЛАДР
#для Postgresql
#

# the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# the temp directory used, within $DIR
WORK_DIR=`mktemp -d -p "$DIR"`

# deletes the temp directory
function cleanup {
  rm -rf "$WORK_DIR"
  echo "Deleted temp working directory $WORK_DIR"
}

# register the cleanup function to be called on the EXIT signal
trap cleanup EXIT

cd "$WORK_DIR"

#Скачивание файла
wget http://www.gnivc.ru/html/gnivcsoft/KLADR/Base.7z

#Распаковка
p7zip -d Base.7z

# dbf to PG sql
pgdbf -s 866 ALTNAMES.dbf | psql -d kladr -U postgres
pgdbf -s 866 DOMA.dbf code "lower(name)" | psql -d kladr -U postgres
pgdbf -s 866 FLAT.dbf code "lower(name)" | psql -d kladr -U postgres
pgdbf -s 866 KLADR.dbf code "lower(name)" | psql -d kladr -U postgres
pgdbf -s 866 SOCRBASE.dbf | psql -d kladr -U postgres
pgdbf -s 866 STREET.dbf code "lower(name)" | psql -d kladr -U postgres

psql -d kladr -U postgres -c "DROP INDEX IF EXISTS kladr_code_idx"
psql -d kladr -U postgres -c "CREATE INDEX kladr_code_idx ON kladr (code)"

#Индекс по улицам нас пунктов и городов
psql -d kladr -U postgres -c "UPDATE street SET code_part = substr(code,1,11)"
psql -d kladr -U postgres -c "DROP INDEX IF EXISTS street_code_part_idx"
psql -d kladr -U postgres -c "CREATE INDEX street_code_part_idx ON street (code_part)"

#Отметка об установке
psql -d kladr -U postgres -c "INSERT INTO update_date VALUES(now())"

#Права
psql -d kladr -U postgres -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO PUBLIC";
